name: Lint

on: [push, pull_request]

jobs:
  SwiftLint UIC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.0.1
        with:
          args: --strict
  SwiftLint Manager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cd Manager
      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.0.1
        with:
          args: --strict
